/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedDmRouteImport } from './routes/_authenticated/dm'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedCCommunityIdRouteRouteImport } from './routes/_authenticated/c/$communityId/route'
import { Route as AuthenticatedDmDmIdRouteImport } from './routes/_authenticated/dm/$dmId'
import { Route as AuthenticatedInviteCodeRouteImport } from './routes/_authenticated/invite.$code'
import { Route as AuthenticatedUUserIdRouteImport } from './routes/_authenticated/u/$userId'
import { Route as AuthenticatedCCommunityIdIndexRouteImport } from './routes/_authenticated/c/$communityId/index'
import { Route as AuthenticatedCCommunityIdCalendarRouteImport } from './routes/_authenticated/c/$communityId/calendar'
import { Route as AuthenticatedCCommunityIdEventsRouteImport } from './routes/_authenticated/c/$communityId/events'
import { Route as AuthenticatedCCommunityIdMediaRouteImport } from './routes/_authenticated/c/$communityId/media'
import { Route as AuthenticatedCCommunityIdPostsRouteImport } from './routes/_authenticated/c/$communityId/posts'
import { Route as AuthenticatedCCommunityIdSettingsRouteImport } from './routes/_authenticated/c/$communityId/settings'
import { Route as AuthenticatedCCommunityIdTasksRouteImport } from './routes/_authenticated/c/$communityId/tasks'
import { Route as AuthenticatedCCommunityIdChChannelIdRouteImport } from './routes/_authenticated/c/$communityId/ch/$channelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDmRoute = AuthenticatedDmRouteImport.update({
  id: '/dm',
  path: '/dm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCCommunityIdRouteRoute =
  AuthenticatedCCommunityIdRouteRouteImport.update({
    id: '/c/$communityId',
    path: '/c/$communityId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDmDmIdRoute = AuthenticatedDmDmIdRouteImport.update({
  id: '/$dmId',
  path: '/$dmId',
  getParentRoute: () => AuthenticatedDmRoute,
} as any)
const AuthenticatedInviteCodeRoute = AuthenticatedInviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUUserIdRoute = AuthenticatedUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCCommunityIdIndexRoute =
  AuthenticatedCCommunityIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCCommunityIdRouteRoute,
  } as any)
const AuthenticatedCCommunityIdCalendarRoute =
  AuthenticatedCCommunityIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedCCommunityIdRouteRoute,
  } as any)
const AuthenticatedCCommunityIdEventsRoute =
  AuthenticatedCCommunityIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedCCommunityIdRouteRoute,
  } as any)
const AuthenticatedCCommunityIdMediaRoute =
  AuthenticatedCCommunityIdMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AuthenticatedCCommunityIdRouteRoute,
  } as any)
const AuthenticatedCCommunityIdPostsRoute =
  AuthenticatedCCommunityIdPostsRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => AuthenticatedCCommunityIdRouteRoute,
  } as any)
const AuthenticatedCCommunityIdSettingsRoute =
  AuthenticatedCCommunityIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCCommunityIdRouteRoute,
  } as any)
const AuthenticatedCCommunityIdTasksRoute =
  AuthenticatedCCommunityIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedCCommunityIdRouteRoute,
  } as any)
const AuthenticatedCCommunityIdChChannelIdRoute =
  AuthenticatedCCommunityIdChChannelIdRouteImport.update({
    id: '/ch/$channelId',
    path: '/ch/$channelId',
    getParentRoute: () => AuthenticatedCCommunityIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/dm': typeof AuthenticatedDmRouteWithChildren
  '/friends': typeof AuthenticatedFriendsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/c/$communityId': typeof AuthenticatedCCommunityIdRouteRouteWithChildren
  '/dm/$dmId': typeof AuthenticatedDmDmIdRoute
  '/invite/$code': typeof AuthenticatedInviteCodeRoute
  '/u/$userId': typeof AuthenticatedUUserIdRoute
  '/c/$communityId/calendar': typeof AuthenticatedCCommunityIdCalendarRoute
  '/c/$communityId/events': typeof AuthenticatedCCommunityIdEventsRoute
  '/c/$communityId/media': typeof AuthenticatedCCommunityIdMediaRoute
  '/c/$communityId/posts': typeof AuthenticatedCCommunityIdPostsRoute
  '/c/$communityId/settings': typeof AuthenticatedCCommunityIdSettingsRoute
  '/c/$communityId/tasks': typeof AuthenticatedCCommunityIdTasksRoute
  '/c/$communityId/': typeof AuthenticatedCCommunityIdIndexRoute
  '/c/$communityId/ch/$channelId': typeof AuthenticatedCCommunityIdChChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/dm': typeof AuthenticatedDmRouteWithChildren
  '/friends': typeof AuthenticatedFriendsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/dm/$dmId': typeof AuthenticatedDmDmIdRoute
  '/invite/$code': typeof AuthenticatedInviteCodeRoute
  '/u/$userId': typeof AuthenticatedUUserIdRoute
  '/c/$communityId/calendar': typeof AuthenticatedCCommunityIdCalendarRoute
  '/c/$communityId/events': typeof AuthenticatedCCommunityIdEventsRoute
  '/c/$communityId/media': typeof AuthenticatedCCommunityIdMediaRoute
  '/c/$communityId/posts': typeof AuthenticatedCCommunityIdPostsRoute
  '/c/$communityId/settings': typeof AuthenticatedCCommunityIdSettingsRoute
  '/c/$communityId/tasks': typeof AuthenticatedCCommunityIdTasksRoute
  '/c/$communityId': typeof AuthenticatedCCommunityIdIndexRoute
  '/c/$communityId/ch/$channelId': typeof AuthenticatedCCommunityIdChChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/dm': typeof AuthenticatedDmRouteWithChildren
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/c/$communityId': typeof AuthenticatedCCommunityIdRouteRouteWithChildren
  '/_authenticated/dm/$dmId': typeof AuthenticatedDmDmIdRoute
  '/_authenticated/invite/$code': typeof AuthenticatedInviteCodeRoute
  '/_authenticated/u/$userId': typeof AuthenticatedUUserIdRoute
  '/_authenticated/c/$communityId/calendar': typeof AuthenticatedCCommunityIdCalendarRoute
  '/_authenticated/c/$communityId/events': typeof AuthenticatedCCommunityIdEventsRoute
  '/_authenticated/c/$communityId/media': typeof AuthenticatedCCommunityIdMediaRoute
  '/_authenticated/c/$communityId/posts': typeof AuthenticatedCCommunityIdPostsRoute
  '/_authenticated/c/$communityId/settings': typeof AuthenticatedCCommunityIdSettingsRoute
  '/_authenticated/c/$communityId/tasks': typeof AuthenticatedCCommunityIdTasksRoute
  '/_authenticated/c/$communityId/': typeof AuthenticatedCCommunityIdIndexRoute
  '/_authenticated/c/$communityId/ch/$channelId': typeof AuthenticatedCCommunityIdChChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/discover'
    | '/dm'
    | '/friends'
    | '/home'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/settings'
    | '/c/$communityId'
    | '/dm/$dmId'
    | '/invite/$code'
    | '/u/$userId'
    | '/c/$communityId/calendar'
    | '/c/$communityId/events'
    | '/c/$communityId/media'
    | '/c/$communityId/posts'
    | '/c/$communityId/settings'
    | '/c/$communityId/tasks'
    | '/c/$communityId/'
    | '/c/$communityId/ch/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/discover'
    | '/dm'
    | '/friends'
    | '/home'
    | '/notifications'
    | '/saved'
    | '/search'
    | '/settings'
    | '/dm/$dmId'
    | '/invite/$code'
    | '/u/$userId'
    | '/c/$communityId/calendar'
    | '/c/$communityId/events'
    | '/c/$communityId/media'
    | '/c/$communityId/posts'
    | '/c/$communityId/settings'
    | '/c/$communityId/tasks'
    | '/c/$communityId'
    | '/c/$communityId/ch/$channelId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/discover'
    | '/_authenticated/dm'
    | '/_authenticated/friends'
    | '/_authenticated/home'
    | '/_authenticated/notifications'
    | '/_authenticated/saved'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/c/$communityId'
    | '/_authenticated/dm/$dmId'
    | '/_authenticated/invite/$code'
    | '/_authenticated/u/$userId'
    | '/_authenticated/c/$communityId/calendar'
    | '/_authenticated/c/$communityId/events'
    | '/_authenticated/c/$communityId/media'
    | '/_authenticated/c/$communityId/posts'
    | '/_authenticated/c/$communityId/settings'
    | '/_authenticated/c/$communityId/tasks'
    | '/_authenticated/c/$communityId/'
    | '/_authenticated/c/$communityId/ch/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dm': {
      id: '/_authenticated/dm'
      path: '/dm'
      fullPath: '/dm'
      preLoaderRoute: typeof AuthenticatedDmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/$communityId': {
      id: '/_authenticated/c/$communityId'
      path: '/c/$communityId'
      fullPath: '/c/$communityId'
      preLoaderRoute: typeof AuthenticatedCCommunityIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dm/$dmId': {
      id: '/_authenticated/dm/$dmId'
      path: '/$dmId'
      fullPath: '/dm/$dmId'
      preLoaderRoute: typeof AuthenticatedDmDmIdRouteImport
      parentRoute: typeof AuthenticatedDmRoute
    }
    '/_authenticated/invite/$code': {
      id: '/_authenticated/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof AuthenticatedInviteCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$userId': {
      id: '/_authenticated/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof AuthenticatedUUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/c/$communityId/': {
      id: '/_authenticated/c/$communityId/'
      path: '/'
      fullPath: '/c/$communityId/'
      preLoaderRoute: typeof AuthenticatedCCommunityIdIndexRouteImport
      parentRoute: typeof AuthenticatedCCommunityIdRouteRoute
    }
    '/_authenticated/c/$communityId/calendar': {
      id: '/_authenticated/c/$communityId/calendar'
      path: '/calendar'
      fullPath: '/c/$communityId/calendar'
      preLoaderRoute: typeof AuthenticatedCCommunityIdCalendarRouteImport
      parentRoute: typeof AuthenticatedCCommunityIdRouteRoute
    }
    '/_authenticated/c/$communityId/events': {
      id: '/_authenticated/c/$communityId/events'
      path: '/events'
      fullPath: '/c/$communityId/events'
      preLoaderRoute: typeof AuthenticatedCCommunityIdEventsRouteImport
      parentRoute: typeof AuthenticatedCCommunityIdRouteRoute
    }
    '/_authenticated/c/$communityId/media': {
      id: '/_authenticated/c/$communityId/media'
      path: '/media'
      fullPath: '/c/$communityId/media'
      preLoaderRoute: typeof AuthenticatedCCommunityIdMediaRouteImport
      parentRoute: typeof AuthenticatedCCommunityIdRouteRoute
    }
    '/_authenticated/c/$communityId/posts': {
      id: '/_authenticated/c/$communityId/posts'
      path: '/posts'
      fullPath: '/c/$communityId/posts'
      preLoaderRoute: typeof AuthenticatedCCommunityIdPostsRouteImport
      parentRoute: typeof AuthenticatedCCommunityIdRouteRoute
    }
    '/_authenticated/c/$communityId/settings': {
      id: '/_authenticated/c/$communityId/settings'
      path: '/settings'
      fullPath: '/c/$communityId/settings'
      preLoaderRoute: typeof AuthenticatedCCommunityIdSettingsRouteImport
      parentRoute: typeof AuthenticatedCCommunityIdRouteRoute
    }
    '/_authenticated/c/$communityId/tasks': {
      id: '/_authenticated/c/$communityId/tasks'
      path: '/tasks'
      fullPath: '/c/$communityId/tasks'
      preLoaderRoute: typeof AuthenticatedCCommunityIdTasksRouteImport
      parentRoute: typeof AuthenticatedCCommunityIdRouteRoute
    }
    '/_authenticated/c/$communityId/ch/$channelId': {
      id: '/_authenticated/c/$communityId/ch/$channelId'
      path: '/ch/$channelId'
      fullPath: '/c/$communityId/ch/$channelId'
      preLoaderRoute: typeof AuthenticatedCCommunityIdChChannelIdRouteImport
      parentRoute: typeof AuthenticatedCCommunityIdRouteRoute
    }
  }
}

interface AuthenticatedDmRouteChildren {
  AuthenticatedDmDmIdRoute: typeof AuthenticatedDmDmIdRoute
}

const AuthenticatedDmRouteChildren: AuthenticatedDmRouteChildren = {
  AuthenticatedDmDmIdRoute: AuthenticatedDmDmIdRoute,
}

const AuthenticatedDmRouteWithChildren = AuthenticatedDmRoute._addFileChildren(
  AuthenticatedDmRouteChildren,
)

interface AuthenticatedCCommunityIdRouteRouteChildren {
  AuthenticatedCCommunityIdCalendarRoute: typeof AuthenticatedCCommunityIdCalendarRoute
  AuthenticatedCCommunityIdEventsRoute: typeof AuthenticatedCCommunityIdEventsRoute
  AuthenticatedCCommunityIdMediaRoute: typeof AuthenticatedCCommunityIdMediaRoute
  AuthenticatedCCommunityIdPostsRoute: typeof AuthenticatedCCommunityIdPostsRoute
  AuthenticatedCCommunityIdSettingsRoute: typeof AuthenticatedCCommunityIdSettingsRoute
  AuthenticatedCCommunityIdTasksRoute: typeof AuthenticatedCCommunityIdTasksRoute
  AuthenticatedCCommunityIdIndexRoute: typeof AuthenticatedCCommunityIdIndexRoute
  AuthenticatedCCommunityIdChChannelIdRoute: typeof AuthenticatedCCommunityIdChChannelIdRoute
}

const AuthenticatedCCommunityIdRouteRouteChildren: AuthenticatedCCommunityIdRouteRouteChildren =
  {
    AuthenticatedCCommunityIdCalendarRoute:
      AuthenticatedCCommunityIdCalendarRoute,
    AuthenticatedCCommunityIdEventsRoute: AuthenticatedCCommunityIdEventsRoute,
    AuthenticatedCCommunityIdMediaRoute: AuthenticatedCCommunityIdMediaRoute,
    AuthenticatedCCommunityIdPostsRoute: AuthenticatedCCommunityIdPostsRoute,
    AuthenticatedCCommunityIdSettingsRoute:
      AuthenticatedCCommunityIdSettingsRoute,
    AuthenticatedCCommunityIdTasksRoute: AuthenticatedCCommunityIdTasksRoute,
    AuthenticatedCCommunityIdIndexRoute: AuthenticatedCCommunityIdIndexRoute,
    AuthenticatedCCommunityIdChChannelIdRoute:
      AuthenticatedCCommunityIdChChannelIdRoute,
  }

const AuthenticatedCCommunityIdRouteRouteWithChildren =
  AuthenticatedCCommunityIdRouteRoute._addFileChildren(
    AuthenticatedCCommunityIdRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedDmRoute: typeof AuthenticatedDmRouteWithChildren
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCCommunityIdRouteRoute: typeof AuthenticatedCCommunityIdRouteRouteWithChildren
  AuthenticatedInviteCodeRoute: typeof AuthenticatedInviteCodeRoute
  AuthenticatedUUserIdRoute: typeof AuthenticatedUUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedDmRoute: AuthenticatedDmRouteWithChildren,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCCommunityIdRouteRoute:
    AuthenticatedCCommunityIdRouteRouteWithChildren,
  AuthenticatedInviteCodeRoute: AuthenticatedInviteCodeRoute,
  AuthenticatedUUserIdRoute: AuthenticatedUUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
